export const metadata = {
  title: 'All - AirRooms',
  description: 'Generated by create next app',
};

export default function RoomsLayout({ children }) {
  return <main className='rooms'>{children}</main>;
}
