export const metadata = {
  title: "All Rooms - Homeey - find your room",
  description: "Generated by create next app",
};

export default function AllRoomsLayout({ children }) {
  return <main>{children}</main>;
}
