export const metadata = {
  title: 'Room - AirRooms',
  description: 'Generated by create next app',
};

export default function RoomLayout({ children }) {
  return <main className='room'>{children}</main>;
}
