export const metadata = {
  title: "Login - Homeey login page",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return <main>{children}</main>;
}
