export const metadata = {
  title: "Sign up - NextHotel App",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return <main>{children}</main>;
}
